//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMU_Mapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMU_Mapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static class Classes
        ///{
        ///    public static XElement _xml = null;
        ///    public static XNamespace _ns;
        ///    public static string _IMAN_master_form;
        ///
        ///    static private XElement[] _getMasterForm(XElement obj, string StorageClass)
        ///    {
        ///        var islandElements = Islands[obj.Attribute(&quot;island_id&quot;).Value];
        ///
        ///        var MasterForm = (from im in islandElements.Where(x =&gt; x.Name.LocalName == &quot;ImanRelation&quot;)
        ///                          join mForm in islandElements.Where(x =&gt; x.Name.LocalName == &quot;Form&quot;) on im.A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private static Dictionary&lt;string, string&gt; LoadLookup(string path)
        ///                {
        ///                        Dictionary&lt;string, string&gt; LoadLookup_d = new Dictionary&lt;string, string&gt;();
        ///                        try
        ///                        {
        ///                            LoadLookup_d = System.IO.File.ReadAllLines(path).Select(x =&gt; x.Split(&apos;|&apos;)).ToDictionary(x =&gt; x[0], x =&gt; x[1]);
        ///      
        ///                            if(LoadLookup_d.Count() == 0)
        ///                            System.Console.WriteLine(&quot;Warning  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompileCode {
            get {
                return ResourceManager.GetString("CompileCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static bool CreateNewAccessDatabase()
        ///    {
        ///
        ///		System.Console.WriteLine(&quot;CreateNewAccessDatabase()&quot;);
        ///        bool result = false;
        ///
        ///        string connectionString = &quot;DataSource=\&quot;test.sdf\&quot;; Password=\&quot;mypassword\&quot;&quot;;
        ///        SqlCeEngine en = new SqlCeEngine(connectionString);
        ///        en.CreateDatabase();
        ///
        ///        SqlCeConnection conn = null;
        ///
        ///		result = true;
        ///
        ///        try
        ///        {
        ///            conn = new SqlCeConnection(connectionString);
        ///            conn.Open();
        ///
        ///			//CREATE TABL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateAccesDatabase {
            get {
                return ResourceManager.GetString("CreateAccesDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class ErrorList : List&lt;ErrorList.ErrorInfo&gt;
        ///{
        ///    public new void Add(ErrorInfo item)
        ///    {
        ///        //check if ignored
        ///
        ///        base.Add(item);
        ///    }
        ///
        ///    public class ErrorInfo
        ///    {
        ///        public enum ErrorCodes : int
        ///        {
        ///            ///&lt;summary&gt;Item missing MasterForm&lt;/summary&gt;
        ///            [Description(&quot;Item missing MasterForm&quot;)]
        ///            [ErrorType(ErrorType.ErrorTypes.OptionalFatal)]
        ///            E101 = 101,
        ///
        ///            ///&lt;summary&gt;ItemRevision missing MasterForm&lt;/sum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:mstns=&quot;http://tempuri.org/myschema/unique&quot;&gt;
        ///  &lt;xs:element name=&quot;maps&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;header&quot;&gt;
        ///          &lt;xs:annotation&gt;
        ///            &lt;xs:documentation&gt;Defines a container for introductory content.&lt;/xs:documentation&gt;
        ///          &lt;/xs:annotation&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MMLSchema {
            get {
                return ResourceManager.GetString("MMLSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static class StringExtension
        ///{
        ///    public static string[] Split(this string str, string splitter)
        ///    {
        ///        return str.Split(new[] { splitter }, System.StringSplitOptions.None);
        ///    }
        ///
        ///    public static string Trunc(this string value, byte maxLength)
        ///    {
        ///        if (string.IsNullOrEmpty(value)) return value;
        ///        return value.Length &lt;= maxLength ? value : value.Substring(0, maxLength);
        ///    }
        ///}.
        /// </summary>
        internal static string StringExtensions {
            get {
                return ResourceManager.GetString("StringExtensions", resourceCulture);
            }
        }
    }
}
